# Generated by Django 4.1.5 on 2023-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=200)),
                ('passengers', models.DecimalField(decimal_places=2, max_digits=5)),
                ('doors', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gearbox', models.CharField(max_length=200)),
                ('file', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
    ]
