# Generated by Django 4.1.5 on 2023-09-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='file',
        ),
    ]
