# Generated by Django 4.1.5 on 2023-09-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2020, max_digits=5),
        ),
    ]
