# Generated by Django 4.1.5 on 2023-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
